{
 "title": "Container",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Container",
    "label": "Container",
    "query": {
     "query": "label_values(container_cpu_system_seconds_total,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU-Usage (cAdvisor)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_system_seconds_total{name=\"$Container\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU system usage"
    },
    {
     "expr": "rate(container_cpu_user_seconds_total{name=\"$Container\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU user usage"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"$Container\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU total usage"
    }
   ]
  },
  {
   "title": "FileSystem (cAdvisor)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_fs_io_current{name=\"$Container\"}[$__rate_interval]) * 100",
     "legendFormat": "FS IO Current"
    },
    {
     "expr": "rate(container_fs_io_time_seconds_total{name=\"$Container\"}[$__rate_interval]) * 100",
     "legendFormat": "FS IO rate"
    }
   ]
  },
  {
   "title": "Memory (cAdvisor)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{name=\"$Container\"}[$__rate_interval])",
     "legendFormat": "memory usage"
    }
   ]
  },
  {
   "title": "Network (cAdvisor)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{name=\"$Container\"}[$__rate_interval])",
     "legendFormat": "network receive rate"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{name=\"$Container\"}[$__rate_interval])",
     "legendFormat": "network transmit rate"
    }
   ]
  }
 ]
}