{
 "title": "InfluxDB",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(http_api_request_duration_seconds_sum{method=\"POST\"}[$__rate_interval])",
     "legendFormat": "Duration Seconds"
    },
    {
     "expr": "rate(query_influxdb_source_read_request_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "Duration Count"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A/60", "type": "math" }
   ]
  },
  {
   "title": "CPU_UTILIZATION (metric)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"STREAM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"CPU_UTILIZATION\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "PUBLISHER_FREQUENCY (metric)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "from(bucket: \"STREAM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PUBLISHINGRATE\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}