{
 "title": "Process",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Process",
    "label": "Process",
    "query": {
     "query": "label_values(namedprocess_namegroup_cpu_seconds_total,groupname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "seconds total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_cpu_seconds_total{groupname=\"datamgmt\"})",
     "legendFormat": "datamgmt/cpu"
    },
    {
     "expr": "sum(namedprocess_namegroup_cpu_seconds_total{groupname=\"structural\"})",
     "legendFormat": "structural/cpu"
    },
    {
     "expr": "sum(namedprocess_namegroup_cpu_seconds_total{groupname=\"continuous\"})",
     "legendFormat": "continuous/cpu"
    },
    {
     "expr": "container_cpu_usage_seconds_total{name=\"neo4j\"}",
     "legendFormat": "neo4j/cpu"
    },
    {
     "expr": "container_cpu_usage_seconds_total{name=\"influxdb\"}",
     "legendFormat": "influxdb/cpu"
    },
    {
     "expr": "sum(namedprocess_namegroup_cpu_seconds_total{groupname=\"ros2talker\"})",
     "legendFormat": "ros2talker/cpu"
    },
    {
     "expr": "sum(namedprocess_namegroup_cpu_seconds_total{groupname=\"ros2listener\"})",
     "legendFormat": "ros2listener/cpu"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "description": "bytes current",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "namedprocess_namegroup_memory_bytes",
     "legendFormat": "{{groupname}}/{{memtype}}"
    },
    {
     "expr": "container_memory_usage_bytes{name=~\"influxdb|neo4j\"}",
     "legendFormat": "{{name}}/memusage"
    },
    {
     "expr": "container_memory_rss{name=~\"influxdb|neo4j\"}",
     "legendFormat": "{{name}}/memrss"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "bytes total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{name=~\"influxdb|neo4j\"}",
     "legendFormat": "{{name}}/transmitted"
    },
    {
     "expr": "container_network_receive_bytes_total{name=~\"influxdb|neo4j\"}",
     "legendFormat": "{{name}}/received"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "timeseries",
   "description": "bytes total",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "container_fs_writes_bytes_total{name=~\"influxdb|neo4j\"}",
     "legendFormat": "{{name}}/write"
    },
    {
     "expr": "container_fs_reads_bytes_total{name=~\"influxdb|neo4j\"}",
     "legendFormat": "{{name}}/read"
    }
   ]
  }
 ]
}