services:
  neo4j:
    image: neo4j:5.26.1
    container_name: neo4j
    # network_mode: "host"
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/123456789
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*

  influxdb:
    container_name: influxdb
    image: influxdb:2.7.11
    # network_mode: "host"
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: KARTOFF8xE
      DOCKER_INFLUXDB_INIT_PASSWORD: 123456789
      DOCKER_INFLUXDB_INIT_ORG: TUBAF
      DOCKER_INFLUXDB_INIT_BUCKET: STREAM
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: WVvSEEbHPqeMFpcgWqThaEcU6u6SWJ-L26ct4oRuEJmKdMOk-ZG8XlKA5xcitJXENa2r2YNLNwxjE6-KKkx8xw==

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    # network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # network_mode: "host"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./configs:/etc/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus-noDevcontainer.yml
    restart: always
    depends_on:
      - influxdb
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # network_mode: "host"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - influxdb
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
      - ./configs/grafana/provisionings/dashboards:/etc/grafana/provisioning/dashboards
      - ./configs/grafana/provisionings/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage:
