global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'influxdb'
    static_configs:
      - targets: ['influxdb:8086']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
